#
# Good to know:
# * This is essentially a copy of ci.yml from Voila
# * secrets.GITHUB_TOKEN is provided by GitHub actions, i.e. it is not a custom/personal token
#

name: ci

on: [push, pull_request, workflow_dispatch]

env:
  RELEASE_DIR: tmp_release

jobs:
  test-and-assemble:
    runs-on: ubuntu-latest
    container: gobraverifier/gobra-base:v5_z3_4.8.7 # Thank you, Gobra team
    steps:
      # Install JDK
#       - uses: actions/setup-java@v2
#         with:
#           distribution: 'adopt' # See https://github.com/marketplace/actions/setup-java-jdk
#           java-version: '11'

      # Checkout Silicon (note: all checkouts delete the contents of their working directory)
      - name: Checkout Silicon
        uses: actions/checkout@v6
        with:
          submodules: true

      # Query versions, and other details that may help with reconstructing a built. 
      # Results are displayed on stdio, and written to buildinfo.log
      - name: Query current date 
        run: printf -- "------- Timestamp --------\n%s\n\n" "$(date +"%Y-%m-%d %H:%M")" | tee -a buildinfo.log
      - name: Query Java version
        run: printf -- "------- Java version --------\n%s\n\n" "$(java --version)" | tee -a buildinfo.log
      - name: Query Z3 version
        run: printf -- "------- Z3 version --------\n%s\n\n" "$(z3 -version)" | tee -a buildinfo.log
      - name: Query Silicon commit
        run: printf -- "------- Silicon commit --------\n%s\n\n" "$(git -C . log --format=reference -n 1 HEAD)" | tee -a buildinfo.log
      - name: Query Silver commit
        run: printf -- "------- Silver commit --------\n%s\n\n" "$(git -C silver log --format=reference -n 1 HEAD)" | tee -a buildinfo.log

      - name: Set sbt cache variables
        # Cache path is relative to the directory in which sbt is invoked
        run: echo "SBT_OPTS=-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy" >> $GITHUB_ENV
      - name: Cache sbt
        uses: actions/cache@v5
        with:
          path: |
            sbt-cache/.sbtboot
            sbt-cache/.boot
            sbt-cache/.ivy/cache
          # <x>/project/target and <x>/target, where <x> is e.g. 'voila' or 'silicon', are intentionally not
          # included as several occurrences of NoSuchMethodError exceptions have been observed during CI runs. 
          # It seems that sbt is unable to correctly compute source files that require a recompilation. 
          # Compiled source files are therefore not cached.
          key: ${{ runner.os }}-sbt-no-precompiled-sources-${{ hashFiles('**/build.sbt') }}

      # - name: Execute a single test only
      #   run: sbt "testOnly -- -n arithmetic.vpr"
      - name: Execute all tests
        run: sbt test
        
      - name: Assemble Silicon fat jar
        run: |
          sbt assembly
          cp target/scala-2.13/silicon.jar .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: test-and-assemble
          path: |
            silicon.jar
            buildinfo.log
          retention-days: 14
          if-no-files-found: error
# #       - name: Create an official release
# #         if: startsWith(github.ref, 'refs/tags/releases/')
# #         uses: softprops/action-gh-release@v3
# #         with:
# #           prerelease: false
# #           files: ${{ env.RELEASE_DIR }}     
# #         env:
# #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
